name: explain_this
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+5

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.15.1
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^10.0.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  in_app_purchase: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  

flutter_native_splash:
  color: "#F7F4FF"
  image: assets/icon/app_icon.png

  android: true
  ios: true

  android_gravity: center
  ios_content_mode: center


  color_dark: "#EDE8FF"
  image_dark: assets/icon/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/debug_sample.jpg
    - assets/icon/app_icon.png